version: '2'

services: 
  master:
    image: danielpalstra/saltstack:master
    command: salt-master -l info
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/minion
  minion:
    image: danielpalstra/saltstack:minion  
    command: salt-minion -l info
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/master
    depends_on: 
      - master
