version: '2'

services: 
  master:
    image: danielpalstra/saltstack:master
    build:
      context: .
      dockerfile: Dockerfile.master
    command: salt-master -l info
  minion:
    image: danielpalstra/saltstack:minion  
    build:
      context: .
      dockerfile: Dockerfile.minion
    # volumes:
    #   - ${PWD}/minion/conf:/etc/salt§
    command: salt-minion -l info
    depends_on: 
      - master
